export default [
    {
        title: 'Strona Główna',
        icon: 'mdi:home',
        path: '/',
        tooltip: 'Przejdź do strony głównej',
    },

    {
        title: 'Konsultacje',
        permission: ['consultations'],
        path: '/consultations',
        collapsible: true,
        items: [
            {
                title: 'Twoje Konsultacje',
                icon: 'mdi:calendar',
                path: '/consultations/calendar',
                permission: ['teacher', 'classteacher'],
                tooltip: 'Zobacz swoje konsultacje',
            },
            {
                title: 'Historia Konsultacji',
                icon: 'mdi:calendar-check',
                path: '/consultations/history',
                permission: ['teacher', 'classteacher'],
                tooltip: 'Przejrzyj historię konsultacji',
            },
        ],
    },
    {
        title: 'Radiowęzeł',
        permission: ['radio'],
        path: '/radio',
        collapsible: true,
        items: [
            {
                title: 'Statystyki',
                icon: 'mdi:chart-bar',
                path: '/radio/statistics',
                permission: ['radio', 'admin'],
                tooltip: 'Zobacz statystyki radiowęzła',
            },
            {
                title: 'Piosenki',
                icon: 'mdi:music',
                path: '/radio/songs',
                permission: ['radio'],
                tooltip: 'Przeglądaj piosenki',
            },
            {
                title: 'Kolejka',
                icon: 'mdi:queue-music',
                path: '/radio/queue',
                permission: ['radio'],
                tooltip: 'Zarządzaj kolejką piosenek',
            },
            {
                title: 'Historia',
                icon: 'mdi:history',
                path: '/radio/history',
                permission: ['radio'],
                tooltip: 'Przeglądaj historię odtwarzania',
            },
        ],
    },
    {
        title: 'E-Sport',
        permission: ['esport'],
        path: '/esport',
        collapsible: true,
        items: [
            {
                title: 'Kalendarz Eventów',
                icon: 'mdi:calendar',
                path: '/esport/calendar',
                permission: ['esport'],
                tooltip: 'Zobacz kalendarz eventów',
            },
            {
                title: 'Historia Eventów',
                icon: 'mdi:history',
                path: '/esport/history',
                permission: ['esport'],
                tooltip: 'Przeglądaj historię eventów',
            },
            {
                title: 'Panel Zespołu',
                icon: 'mdi:cog',
                path: '/esport/panel',
                permission: ['esport', 'admin'],
                tooltip: 'Zarządzaj zespołem',
            },
        ],
    },
    {
        title: 'Wychowawca',
        permission: ['classteacher'],
        path: '/class',
        collapsible: true,
        items: [
            {
                title: 'Twoja Klasa',
                icon: 'mdi:calendar',
                path: '/class/my',
                permission: ['classteacher'],
                tooltip: 'Zobacz swoją klasę',
            },
        ],
    },
    {
        title: 'Administracyjne',
        permission: ['admin'],
        path: '/admin',
        collapsible: true,
        items: [
            {
                title: 'Użytkownicy',
                icon: 'mdi:account-group',
                path: '/admin/users',
                permission: ['admin'],
                tooltip: 'Zarządzaj użytkownikami',
            },
            {
                title: 'Klasy',
                icon: 'mdi:chart-bar',
                path: '/admin/reports',
                permission: ['admin'],
                tooltip: 'Zobacz raporty klas',
            },
            {
                title: 'Statystyki',
                icon: 'mdi:chart-bar',
                path: '/admin/statistics',
                permission: ['admin'],
                tooltip: 'Przeglądaj statystyki',
            },
        ],
    },
    {
        title: 'Super Admin',
        permission: ['superadmin'],
        path: '/superadmin',
        collapsible: true,
        items: [
            {
                title: 'Logi',
                icon: 'mdi:history',
                path: '/superadmin/logs',
                permission: ['superadmin'],
                tooltip: 'Przeglądaj logi systemowe',
            },
            {
                title: 'Panel Superadmina',
                icon: 'mdi:cog',
                path: '/superadmin/panel',
                permission: ['superadmin'],
                tooltip: 'Zarządzaj systemem',
            },
        ],
    },
];
